.TH "vfcrack" 1
.SH NAME
vfcrack \- decrypt encrypted filevault disk images
.SH SYNOPSIS
.B vfcrack
<dict> <dmg> [fpga]
.SH DESCRIPTION
vile fault crack mounts a dictionary attack against a given Mac OS X disk image file. It supports both version 1 and 2 of the non-documented proprietary format. Simply supply a dictionary file and a disk image. You can optionally you can use a pico computing fpga.
.SH "SEE ALSO"
vfdecrypt(1)
.SH BUGS
Feel free to report them or to submit patches.
.SH AUTHORS
Ralf-Philipp Weinmann <ralf@coderpunks.org>
.TP
David Hulton <dhulton@openciphers.org>
.TP
Jacob Appelbaum <jacob@appelbaum.net> 
